# Removed version as it's obsolete in newer Docker Compose

services:
  app:
    build: .
    container_name: corepath-backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///app/corepath.db
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-corepath-secret-key-change-in-production-12345}
      - PROJECT_NAME=CorePath Impact API
      - VERSION=1.0.0
      - API_V1_STR=/api/v1
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=10485760
      - ALLOWED_IMAGE_TYPES=jpg,jpeg,png,gif,webp
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - REFERRAL_POINTS=500
      - SIGNUP_BONUS_POINTS=100
      - ORDER_POINTS_RATE=0.01
      - FROM_EMAIL=noreply@corepathimpact.com
    volumes:
      - ./uploads:/app/uploads
      - db_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - corepath-network

  nginx:
    image: nginx:alpine
    container_name: corepath-nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL certificates
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - corepath-network

volumes:
  db_data:

networks:
  corepath-network:
    driver: bridge